/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AfiliadosRouteImport } from './routes/afiliados'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as AfiliadosRelatorioRouteImport } from './routes/afiliados_.relatorio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRoute = AfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadosRelatorioRoute = AfiliadosRelatorioRouteImport.update({
  id: '/afiliados_/relatorio',
  path: '/afiliados/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/anuncios': typeof AnunciosRoute
  '/clientes': typeof ClientesRoute
  '/integracoes': typeof IntegracoesRoute
  '/mensagens': typeof MensagensRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/afiliados/relatorio': typeof AfiliadosRelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/anuncios': typeof AnunciosRoute
  '/clientes': typeof ClientesRoute
  '/integracoes': typeof IntegracoesRoute
  '/mensagens': typeof MensagensRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/afiliados/relatorio': typeof AfiliadosRelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afiliados': typeof AfiliadosRoute
  '/anuncios': typeof AnunciosRoute
  '/clientes': typeof ClientesRoute
  '/integracoes': typeof IntegracoesRoute
  '/mensagens': typeof MensagensRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/afiliados_/relatorio': typeof AfiliadosRelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliados'
    | '/anuncios'
    | '/clientes'
    | '/integracoes'
    | '/mensagens'
    | '/pedidos'
    | '/produtos'
    | '/afiliados/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliados'
    | '/anuncios'
    | '/clientes'
    | '/integracoes'
    | '/mensagens'
    | '/pedidos'
    | '/produtos'
    | '/afiliados/relatorio'
  id:
    | '__root__'
    | '/'
    | '/afiliados'
    | '/anuncios'
    | '/clientes'
    | '/integracoes'
    | '/mensagens'
    | '/pedidos'
    | '/produtos'
    | '/afiliados_/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfiliadosRoute: typeof AfiliadosRoute
  AnunciosRoute: typeof AnunciosRoute
  ClientesRoute: typeof ClientesRoute
  IntegracoesRoute: typeof IntegracoesRoute
  MensagensRoute: typeof MensagensRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  AfiliadosRelatorioRoute: typeof AfiliadosRelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados': {
      id: '/afiliados'
      path: '/afiliados'
      fullPath: '/afiliados'
      preLoaderRoute: typeof AfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliados_/relatorio': {
      id: '/afiliados_/relatorio'
      path: '/afiliados/relatorio'
      fullPath: '/afiliados/relatorio'
      preLoaderRoute: typeof AfiliadosRelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfiliadosRoute: AfiliadosRoute,
  AnunciosRoute: AnunciosRoute,
  ClientesRoute: ClientesRoute,
  IntegracoesRoute: IntegracoesRoute,
  MensagensRoute: MensagensRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  AfiliadosRelatorioRoute: AfiliadosRelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
